#Tomcat端口号 默认是8080端口
server:
  port: 9099
# Spring配置
spring:
  # jackson时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dormitory?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为8379
    port: 6379
    # 数据库索引（db0，db1，db2...不同业务可以放在不同数据库中）
    database: 2
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池的最大数据库连接数
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000
  # 文件大小上传设置
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
# ChatAI
yuapi:
  client:
    access-key: XXX
    secret-key: XXX